List <Map<String,dynamic>> Products = [
  {
    'p_name': 'Cabage',
    'p_category': 'vegetables',
    'p_price': 120.0,
    'd_price': 100.0,
    'p_image': 'assets/cabage.png',
    'p_desc': "Cabbage is primarily grown for consumption as a vegetable, eaten after boiling or steaming. Some cultivars are grown as fodder for animals. Red cabbage is commonly pickled",
  },
  {
    'p_name': 'Capsicum',
    'p_category': 'vegetables',
    'p_price': 120.0,
    'd_price': 100.0,
    'p_image': 'assets/capsicup.png',
    'p_desc': "Cabbage is primarily grown for consumption as a vegetable, eaten after boiling or steaming. Some cultivars are grown as fodder for animals. Red cabbage is commonly pickled",
  }
  ,
  {
    'p_name': 'carrot',
    'p_category': 'vegetables',
    'p_price': 120.0,
    'd_price': 100.0,
    'p_image': 'assets/carrot.png',
    'p_desc': "Cabbage is primarily grown for consumption as a vegetable, eaten after boiling or steaming. Some cultivars are grown as fodder for animals. Red cabbage is commonly pickled",
  },
  {
    'p_name': 'Coriander',
    'p_category': 'vegetables',
    'p_price': 220.0,
    'd_price': 100.0,
    'p_image': 'assets/coriander.jpg',
    'p_desc': "Cabbage is primarily grown for consumption as a vegetable, eaten after boiling or steaming. Some cultivars are grown as fodder for animals. Red cabbage is commonly pickled",
  },
  {
    'p_name': 'Cucumber',
    'p_category': 'vegetables',
    'p_price': 120.0,
    'd_price': 100.0,
    'p_image': 'assets/cuumber.png',
    'p_desc': "Cabbage is primarily grown for consumption as a vegetable, eaten after boiling or steaming. Some cultivars are grown as fodder for animals. Red cabbage is commonly pickled",
  },
  {
    'p_name': 'Fulkopi',
    'p_category': 'vegetables',
    'p_price': 120.0,
    'd_price': 100.0,
    'p_image': 'assets/fulkopi.jpg',
    'p_desc': "Cabbage is primarily grown for consumption as a vegetable, eaten after boiling or steaming. Some cultivars are grown as fodder for animals. Red cabbage is commonly pickled",
  },
  {
    'p_name': 'Green Chili',
    'p_category': 'vegetables',
    'p_price': 120.0,
    'd_price': 100.0,
    'p_image': 'assets/greenchili.png',
    'p_desc': "Cabbage is primarily grown for consumption as a vegetable, eaten after boiling or steaming. Some cultivars are grown as fodder for animals. Red cabbage is commonly pickled",
  },
  {
    'p_name': 'Onion',
    'p_category': 'vegetables',
    'p_price': 120.0,
    'd_price': 100.0,
    'p_image': 'assets/onion.png',
    'p_desc': "Cabbage is primarily grown for consumption as a vegetable, eaten after boiling or steaming. Some cultivars are grown as fodder for animals. Red cabbage is commonly pickled",
  },
  {
    'p_name': 'Potato',
    'p_category': 'vegetables',
    'p_price': 120.0,
    'd_price': 100.0,
    'p_image': 'assets/potato.png',
    'p_desc': "Cabbage is primarily grown for consumption as a vegetable, eaten after boiling or steaming. Some cultivars are grown as fodder for animals. Red cabbage is commonly pickled",
  },
  {
    'p_name': 'Termeric',
    'p_category': 'vegetables',
    'p_price': 120.0,
    'd_price': 100.0,
    'p_image': 'assets/termeric.png',
    'p_desc': "Cabbage is primarily grown for consumption as a vegetable, eaten after boiling or steaming. Some cultivars are grown as fodder for animals. Red cabbage is commonly pickled",
  },
  {
    'p_name': 'Tomato',
    'p_category': 'vegetables',
    'p_price': 120.0,
    'd_price': 100.0,
    'p_image': 'assets/tomato.png',
    'p_desc': "Cabbage is primarily grown for consumption as a vegetable, eaten after boiling or steaming. Some cultivars are grown as fodder for animals. Red cabbage is commonly pickled",
  }
];